### ISSUE TITLE
Render vs Redirect 관련

### ISSUE THREAD

**Issue by HyunsangHan** [HyunSangHan/study-django#7]
**상황**
2nd_ugc 디렉토리 안에 있는 프로젝트는 뉴스기사 포맷으로 글을 업로드할 수 있는 '비로그인 기반' 서비스임. 특정 글을 수정하기 위해서는 사용자의 depth가 index - show - manage - edit 템플릿을 거쳐야 함. 그런데 manage를 거치지 않고 직접 URL을 통해 edit에 접근을 한 경우에도 글을 수정할 수 있는 문제가 있었음.

[템플릿 설명]
index: 전체 리스트
show: 특정한 하나의 글
manage: 글 작성자인지 인증하는 의도의 페이지(작성 시에 입력했던 패스워드를 성공적으로 입력한 경우에만 글을 수정할 권한을 주기 위함)
edit: 작성했던 글을 수정하는 페이지

**현재 임시 해결방법**
manage와 edit의 view를 하나로 합침. 기본적으로는 manage를 렌더해주고, 패스워드를 POST메소드 통해서 받아 view에서 인증여부를 판단해주되 패스워드를 맞힌 경우에 한해 edit을 리다이렉트가 아닌 '렌더'해줌. 근데 이렇게 POST메소드에서 리다이렉트가 아니라 렌더를 써주는 게 적절한지? 이거 외에 다른 방법은 없을지 의문

    def manage(request, id):
        feed = Feed.objects.get(id=id)
        if (request.method == 'POST') and (feed.password == request.POST['password']) :
            #  일단 렌더를 통해 구현했음!
            # return redirect('/article/%d/edit/'%id)
            return render(request, 'feeds/edit.html', {'feed': feed})  
        else:
            return render(request, 'feeds/manage.html', {'feed': feed})

    # def edit(request, id):
    #     feed = Feed.objects.get(id=id)
    #     return render(request, 'feeds/edit.html', {'feed': feed})

**Comment by qpzm** [comment]
1. 현재 구현에서는 수정 중에 새로고침을 누르면 다시 password 입력창으로 돌아가는 문제가 있겠네요 😯
2. 로그인창을 띄울 때 feed 정보를 불러오는 것이 과연 필요할까요?

**Comment by HyunsangHan** [comment]
1. 맞습니다. 그 문제를 해결하기 위해서는, 템플릿을 기존처럼 manage와 edit로 나누고 token같은 걸 이용해서 인증을 해결해야 하려나요?
2. 앗, 지금 구현에서는 feed가 필요없는데 실수로 넣었네요.

**Comment by qpzm** [comment]
네 그럼 token 혹은 권한 정보를 어디에 저장할 지만 결정하면 되겠네요

**Comment by HyunsangHan** [comment]
> 2. 앗, 지금 구현에서는 feed가 필요없는데 실수로 넣었네요.

아, 일단 이것 관련하여 정정합니다.
이런 부분이 manage.html에 있어서 feed정보가 필요하긴 한 상황이네요.
      \<form action='/article/{{ feed.id }}/edit/' method='POST'>

**Comment by HyunsangHan** [comment]
'인증'이라는 말에 hint를 얻어서 아래와 같이 view를 구성하고 해결했습니다.
뭔가 다른 기법이 필요할까 생각했는데 생각보다 심플한 것으로 해결되어버렸네요..!


    def manage(request, id):
        feed = Feed.objects.get(id=id)
        return render(request, 'feeds/manage.html', {'feed': feed})

    def edit(request, id):
        feed = Feed.objects.get(id=id)
        if (request.method == 'POST') and (feed.password == request.POST['password']) :
            return render(request, 'feeds/edit.html', {'feed': feed})    
        else:
            return redirect('/article/%d/manage/'%id)
